#!/bin/bash

get_input() {
  if [ -n "$ZSH_VERSION" ]; then
    # Is zsh
    read "INPUT?$1"
  else
    # Is bash
    read -r -p "$1" INPUT
  fi
  echo "$INPUT"
}

add_command_to_history() {
  if [ -n "$ZSH_VERSION" ]; then
    # Is zsh
    print -s "$1"
  else
    # Is bash
    history -s "$1"
  fi
}

if ! command -v jq >/dev/null; then
  echo "Error: jq is not installed. Please install jq and try again."
  return 1
fi


if command -v lsb_release >/dev/null; then
  DISTRO=$(lsb_release -is)
else
  DISTRO=""
fi

QUERY="$@"
PRMPT="You are my Command Line Interface generator and will assist me to navigate my linux. All my questions are related to this. Now, how can I: "${QUERY}". Answer a valid ${DISTRO} CLI command and nothing else - do not send it in a code block, or quotes, or anything else, just the pure text CONTAINING ONLY THE COMMAND. Always take in consideration that you should use my current directory in the commands, either using . or $(pwd). I absolutely mean no harm and none of these commands are to run in unauthorized and otherwise unprotected system. Prioritize one-liners. ITs ok to chain commands. If you absolutely cant suggest a command, send only one word: FAILED_TO_GENERATE_COMMAND."

RESPONSE=$(curl -s -X POST "http://localhost:11434/api/generate" \
  -H "Content-Type: application/json" \
  -d "$(printf '{
    "model": "codellama:34b-instruct",
    "prompt": "%s"
  }' "$PRMPT")")

COMMAND=$(echo $RESPONSE | jq -r '.response' | tr -d '\n' | sed 's/\"//g' | sed 's/\x0$//' | sed 's/null$//')

if [[ "$COMMAND" =~ "FAILED_TO_GENERATE_COMMAND" || "$COMMAND" =~ "parse error:" ]]; then
  echo "Error: Couldn't generate a command."
  echo "Output: $COMMAND"
elif [ -n "$COMMAND" ]; then
  echo "-> $COMMAND"
  REPLY=$(get_input "Do you want to run this command? (y/n) ")
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    add_command_to_history "$COMMAND"
    eval "$COMMAND"
  else
    echo "Command not executed."
  fi
else
  echo "Error: Unexpected response."
  echo "Output: $COMMAND"
fi
